### PR TITLE
Remove latitude, longitude and zoom from Country

### LINKED ISSUE #114: Countries export change
In cubing/worldcubeassociation.org/pull/788 `longitude`, `latitude` and `zoom` fields has been removed from Countries table. `Country` class and db export should be updated.

### PR DESCRIPTION
**Pull request by jonatanklosko**
Fixes #114.
I haven't been contributing here before but I hope I've done things right.
These are all the places using `longitude`, `latitude` and `zoom` related to Country.

### CODE REVIEW

**Comment by viroulep** [comment]
I checked it out, and I've no more registrations errors on countries :)

Do you have any idea on how to package a release for this? (I don't, I would guess just bump the version [here](https://github.com/cubing/wca-workbook-assistant/blob/master/build.properties#L1) and upload the jar :p)

**Comment by jonatanklosko** [comment]
@viroulep unfortunately I don't know how to do release stuff.

**Comment by viroulep** [comment]
Ok plan B then.
The PR LGTM as it fixes what should be fixed; I'll send the jar to the results team just for a sanity check, and I'll make a release with it if they validate it!

**Comment by SAuroux** [comment]
Hi Philippe, please put this on hold. We might have another easy fix which does not require a new WA release.

**Comment by viroulep** [comment]
Cool :)

**Comment by jfly** [comment]
Closing this as we were able to work around this without updating the WA.

**Comment by jfly** [comment]
Actually, let's merge this up so we can get rid of the hack introduced in https://github.com/thewca/worldcubeassociation.org/pull/808.

**Pull request merged**
